# Generated by Django 3.2.4 on 2021-12-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id_campus', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('name_short', models.CharField(max_length=20)),
                ('name_campus', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id_campus', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('name_campus', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid_rozklad', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('id_campus', models.PositiveSmallIntegerField(null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('name_rozklad', models.CharField(max_length=20)),
                ('cathedra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mainapp.cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=15, null=True)),
                ('lon', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('url_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('name_normalized', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_campus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug_campus', models.CharField(blank=True, max_length=10, null=True)),
                ('uuid_rozklad', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, choices=[('ас', 'асистент'), ('доц', 'доцент'), ('вик', 'викладач'), ('ст.вик', 'старший викладач'), ('проф', 'професор'), ('зав.каф', 'зав. кафедрою'), ('дек', 'декан')], max_length=10, null=True)),
                ('name', models.CharField(max_length=500)),
                ('name_full', models.CharField(blank=True, max_length=500, null=True)),
                ('name_campus', models.CharField(blank=True, max_length=500, null=True)),
                ('cathedras_rozklad', models.CharField(blank=True, max_length=500, null=True)),
                ('cathedras', models.ManyToManyField(related_name='teachers', to='mainapp.Cathedra')),
            ],
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cathedras', to='mainapp.faculty'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveSmallIntegerField(choices=[(1, 1)])),
                ('week', models.PositiveSmallIntegerField(choices=[(1, 1)])),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('num', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mainapp.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mainapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mainapp.teacher')),
            ],
            options={
                'unique_together': {('group', 'semestr', 'week', 'day', 'num', 'subject', 'teacher')},
            },
        ),
    ]
