# Generated by Django 3.1.5 on 2021-02-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campus', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('name_campus', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campus', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('name_campus', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campus', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('name_rozklad', models.CharField(max_length=20)),
                ('url_rozklad', models.CharField(max_length=500)),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cathedra')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_maps', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_wiki', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_rozklad', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_semestr', models.PositiveSmallIntegerField(choices=[(1, 1)])),
                ('lesson_week', models.PositiveSmallIntegerField(choices=[(1, 1)])),
                ('lesson_day', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('lesson_num', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty'),
        ),
    ]
