# Generated by Django 3.1.5 on 2021-02-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='name_full',
        ),
    ]
