# Generated by Django 3.2.4 on 2021-06-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210618_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cathedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mainapp.cathedra'),
        ),
    ]
